# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
revisionHistoryLimit: 1
image:
  repository: ibmcase/kcontainer-voyages-ms
  tag: latest
  pullPolicy: Always
  pullSecret: null
  resources:
    requests:
      cpu: 200m
      memory: 300Mi
livenessProbe:
  initialDelaySeconds: 3000
  periodSeconds: 1000
service:
  name: node
  type: NodePort
  servicePort: 3000
  nodePort: 31000
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  metrics:
    cpu:
      targetAverageUtilization: 70
    memory:
      targetAverageUtilization: 70
base:
  enabled: false
  replicaCount: 1
  image:
    tag : v0.9.9
  weight: 100
istio:
  enabled: false
  weight: 100
generatedBindings:
  enabled: false
# Individual Routes are preferred over Ingresses on OCP
route:
  enabled: false
  path: /
  urlPrefix: kcontainer-voyagesms
kafka:
  brokersConfigMap: kafka-brokers
  orderTopicName: orders
eventstreams:
  enabled: true
  apikeyConfigMap: eventstreams-apikey
  caPemFileRequired: false
  caPemFilePath: "/etc/ssl/certs/kcontainer"
  caPemFileName: "es-cert.pem"
  caPemSecretName: es-ca-pemfile
serviceAccountName: default
