name: Build & push images for 'kc-ms'
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '**/chart/'

jobs:
  build-docker-images:
    if: startsWith(github.repository, 'ibm-cloud-architecture/')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Bump version and push tag
      id: bump-version-action
      uses: anothrNick/github-tag-action@master
      env:
        DEFAULT_BUMP: patch
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the fleet-ms docker image
      id: build-fleet-image
      run: |
        docker login -u ${DOCKER_U} -p ${DOCKER_P}
        cd ${WORKDIR}
        docker build . --file ${DOCKERFILE} --tag ${IMAGE_NAME}:${IMAGE_TAG}
        docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${IMAGE_NAME}:latest
        docker push ${IMAGE_NAME}
      env:
        DOCKER_U: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_P: ${{ secrets.DOCKER_PASSWORD }}
        WORKDIR: fleet-ms
        DOCKERFILE: Dockerfile.multistage
        IMAGE_NAME: ibmcase/kcontainer-fleet-ms
        IMAGE_TAG: ${{ steps.bump-version-action.outputs.new_tag }}
    - name: Build the voyage-ms docker image
      id: build-voyage-image
      run: |
        docker login -u ${DOCKER_U} -p ${DOCKER_P}
        cd ${WORKDIR}
        docker build . --file ${DOCKERFILE} --tag ${IMAGE_NAME}:${IMAGE_TAG}
        docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${IMAGE_NAME}:latest
        docker push ${IMAGE_NAME}
      env:
        DOCKER_U: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_P: ${{ secrets.DOCKER_PASSWORD }}
        WORKDIR: voyages-ms
        DOCKERFILE: Dockerfile
        IMAGE_NAME: ibmcase/kcontainer-voyages-ms
        IMAGE_TAG: ${{ steps.bump-version-action.outputs.new_tag }}
    - name: Webhook to GitOps repo
      id: gitops-repo-webhook
      uses: osowski/repository-dispatch@v1
      with:
        token: ${{ secrets.WEBHOOK_TOKEN }}
        repository: ibm-cloud-architecture/refarch-kc-gitops
        event-type: gitops-refresh
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "source": "${{ github.repository }}"}'
